# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi_aj:springboard rig_hash set value '1c4477dad064363ae82d9bc928dc798affa09a975b3fc7f60c9605f31fc64c07'
scoreboard objectives add aj.animation_springboard_prime.frame dummy
scoreboard objectives add aj.animation_springboard_bounce.frame dummy