# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function dpi_aj:springboard/animations/animation_springboard_prime/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1