# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=dpi.aj.lev_icons.animation.chest_open.playing] run function dpi:aj/lev_icons/animations/chest_open/zzz/on_tick
execute if entity @s[tag=dpi.aj.lev_icons.animation.chest_close.playing] run function dpi:aj/lev_icons/animations/chest_close/zzz/on_tick
execute if entity @s[tag=dpi.aj.lev_icons.animation.mcf_tick_levitate.playing] run function dpi:aj/lev_icons/animations/mcf_tick_levitate/zzz/on_tick
execute if entity @s[tag=dpi.aj.lev_icons.animation.python_levitate.playing] run function dpi:aj/lev_icons/animations/python_levitate/zzz/on_tick
execute if entity @s[tag=dpi.aj.lev_icons.animation.structure_file_levitate.playing] run function dpi:aj/lev_icons/animations/structure_file_levitate/zzz/on_tick
execute if entity @s[tag=dpi.aj.lev_icons.animation.json_file_levitate.playing] run function dpi:aj/lev_icons/animations/json_file_levitate/zzz/on_tick