# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/chest_house rig_hash set value '38412f3b134128f211be8eb9af943dff2f61d98bca35f2b023c28317501e5b4d'
scoreboard objectives add aj.chest_open.frame dummy
scoreboard objectives add aj.chest_close.frame dummy
scoreboard objectives add aj.mcf_tick_levitate.frame dummy
scoreboard objectives add aj.python_levitate.frame dummy
scoreboard objectives add aj.structure_file_levitate.frame dummy
scoreboard objectives add aj.json_file_levitate.frame dummy
scoreboard objectives add aj.mcf_tick_levitate2.frame dummy
scoreboard objectives add aj.python_levitate2.frame dummy
scoreboard objectives add aj.structure_file_levitate2.frame dummy
scoreboard objectives add aj.json_file_levitate2.frame dummy