# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/chest_house rig_hash set value '8ba39c60e854ba4d341d9450b661b3f09fd556cdb6661c7071efd7ebfe863246'
scoreboard objectives add aj.chest_open.frame dummy
scoreboard objectives add aj.chest_close.frame dummy
scoreboard objectives add aj.mcf_tick_levitate.frame dummy
scoreboard objectives add aj.python_levitate.frame dummy
scoreboard objectives add aj.structure_file_levitate.frame dummy
scoreboard objectives add aj.json_file_levitate.frame dummy