# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/chest_house rig_hash set value '9cd839907390bc634ad64e7423fa92d0937f85255b78a33281faff483009d094'
scoreboard objectives add aj.chest_open.frame dummy
scoreboard objectives add aj.chest_close.frame dummy
scoreboard objectives add aj.mcf_tick_levitate.frame dummy