# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=dpi_aj.springboard.animation.animation_springboard_prime.playing] run function dpi_aj:springboard/animations/animation_springboard_prime/zzz/on_tick
execute if entity @s[tag=dpi_aj.springboard.animation.animation_springboard_bounce.playing] run function dpi_aj:springboard/animations/animation_springboard_bounce/zzz/on_tick
execute on passengers run rotate @s ~ ~