output: "build"

pipeline:
  - data_pack:
      load: ["src"]
    resource_pack:
      load: ["src"]
    require:
      - bolt
      - bolt_expressions
    meta:
      bolt:
        entrypoint:
          "dpi:main"
    pipeline:
      - mecha

  - data_pack:
      load: ["lib"]
    resource_pack:
      load: ["lib"]
