# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.ant_handout_to_busy.frame 0
tag @s add aj.transforms_only
execute at @s run function dpi:aj/creators/animations/ant_handout_to_busy/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove dpi.aj.creators.animation.ant_handout_to_busy.playing