# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi_aj:chest_house rig_hash set value '4a15afe08b26c8cabbd6fbd2edb423594be99a0bd1b5f3a90ff4b409052e81ca'
scoreboard objectives add aj.chest_open.frame dummy
scoreboard objectives add aj.chest_close.frame dummy