# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/creators rig_hash set value 'fb932c3d074fcea9a3700b2dff7372d899e2233f0fd667c32b41bff490889d9c'
scoreboard objectives add aj.bth_busy.frame dummy
scoreboard objectives add aj.bth_idle.frame dummy
scoreboard objectives add aj.amandin_busy.frame dummy
scoreboard objectives add aj.amandin_idle.frame dummy
scoreboard objectives add aj.ant_busy.frame dummy
scoreboard objectives add aj.ant_blowing_balloon.frame dummy
scoreboard objectives add aj.ant_handout_to_busy.frame dummy