# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/creators rig_hash set value '95704dd2c007e923a1e8a8104bac8b9bf28882e99f60ecf522c6caefbd4d42e3'
scoreboard objectives add aj.bth_busy.frame dummy
scoreboard objectives add aj.bth_idle.frame dummy
scoreboard objectives add aj.amandin_busy.frame dummy
scoreboard objectives add aj.amandin_idle.frame dummy
scoreboard objectives add aj.ant_busy.frame dummy
scoreboard objectives add aj.ant_blowing_balloon.frame dummy
scoreboard objectives add aj.ant_handout_to_busy.frame dummy