# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/creators rig_hash set value 'ed93dae545079f857a70ec51014caefa3126bdb61debc90ab06fff17795f527d'
scoreboard objectives add aj.bth_busy.frame dummy
scoreboard objectives add aj.bth_idle.frame dummy
scoreboard objectives add aj.amandin_busy.frame dummy
scoreboard objectives add aj.amandin_idle.frame dummy
scoreboard objectives add aj.ant_busy.frame dummy
scoreboard objectives add aj.ant_blowing_balloon.frame dummy