# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=dpi.aj.creators.animation.main.playing] run function dpi:aj/creators/animations/main/zzz/on_tick
execute if entity @s[tag=dpi.aj.creators.animation.idle_ant.playing] run function dpi:aj/creators/animations/idle_ant/zzz/on_tick
execute if entity @s[tag=dpi.aj.creators.animation.busyant.playing] run function dpi:aj/creators/animations/busyant/zzz/on_tick
execute on passengers run rotate @s ~ ~