# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(baton) {transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,0f,0f,0f,-1f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-1f,0f,0f,-1f,0f,1f,0f,0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head4) {transformation: [-1f,0f,0f,-0.5625f,0f,1f,0f,0.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(display4) {transformation: [-1.8333f,0f,0f,-1.9375f,0f,1.8333f,0f,0.8438f,0f,0f,-1.8333f,1.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(display5) {transformation: [-1.8333f,0f,0f,0.8125f,0f,1.8333f,0f,0.8438f,0f,0f,-1.8333f,1.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}