# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/lev_icons rig_hash set value '48fd5b25a70e78486790c9d7b82330bf4d199cf9fa635e01dcbb756565e7a2b5'
scoreboard objectives add aj.chest_open.frame dummy
scoreboard objectives add aj.chest_close.frame dummy
scoreboard objectives add aj.mcf_tick_levitate.frame dummy
scoreboard objectives add aj.python_levitate.frame dummy
scoreboard objectives add aj.structure_file_levitate.frame dummy
scoreboard objectives add aj.json_file_levitate.frame dummy