# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/lev_icons rig_hash set value '87251b1cda0118f675e89e2ccd7989fe72e5cadb5e5c9f81916c4fad9942ac67'
scoreboard objectives add aj.chest_open.frame dummy
scoreboard objectives add aj.chest_close.frame dummy
scoreboard objectives add aj.mcf_tick_levitate.frame dummy
scoreboard objectives add aj.python_levitate.frame dummy
scoreboard objectives add aj.structure_file_levitate.frame dummy
scoreboard objectives add aj.json_file_levitate.frame dummy