# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.chest_open.frame
scoreboard objectives remove aj.chest_close.frame
scoreboard objectives remove aj.mcf_tick_levitate.frame
scoreboard objectives remove aj.python_levitate.frame
scoreboard objectives remove aj.structure_file_levitate.frame
scoreboard objectives remove aj.json_file_levitate.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (dpi:aj/lev_icons)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'dpi:aj/lev_icons',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']