# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) { transformation: [-10.0219f,0f,0f,0f,0f,10.0219f,0f,9.0197f,0f,0f,-10.0219f,-7.0153f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(chest_house) { transformation: [-9.3538f,0f,0f,0f,0f,9.3538f,0f,0f,0f,0f,-9.3538f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(mcf_tick) { transformation: [-4f,0f,0f,-17.4375f,0f,4f,0f,14.5625f,0f,0f,-4f,10.625f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(python) { transformation: [-4.9147f,0.6637f,1.9621f,13.0903f,0.1741f,5.1666f,-1.3115f,23.4514f,-2.064f,-1.1445f,-4.7827f,-4.25f,0f,0f,0f,1f], start_interpolation: 0 }