# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "dpi:aj/creators"
data modify storage animated_java:temp entry.data.rig_hash set value "40f15bd7720a3314df916d9011ffec15ccc7450db7c2b8ea23a60f75d2a50e0e"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=dpi.aj.creators.node.head1] run function dpi:aj/creators/zzz/summon/as_node/head1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.left_hand2] run function dpi:aj/creators/zzz/summon/as_node/left_hand2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_hand2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.brush] run function dpi:aj/creators/zzz/summon/as_node/brush
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.brush set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.right_hand2] run function dpi:aj/creators/zzz/summon/as_node/right_hand2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_hand2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.display2] run function dpi:aj/creators/zzz/summon/as_node/display2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.display2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.display3] run function dpi:aj/creators/zzz/summon/as_node/display3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.display3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.head] run function dpi:aj/creators/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.left_hand1] run function dpi:aj/creators/zzz/summon/as_node/left_hand1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_hand1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.right_hand1] run function dpi:aj/creators/zzz/summon/as_node/right_hand1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_hand1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.display1] run function dpi:aj/creators/zzz/summon/as_node/display1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.display1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.display] run function dpi:aj/creators/zzz/summon/as_node/display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.display set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.kb] run function dpi:aj/creators/zzz/summon/as_node/kb
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.kb set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.baton] run function dpi:aj/creators/zzz/summon/as_node/baton
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.baton set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.right_hand] run function dpi:aj/creators/zzz/summon/as_node/right_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.left_hand] run function dpi:aj/creators/zzz/summon/as_node/left_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.head4] run function dpi:aj/creators/zzz/summon/as_node/head4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.display4] run function dpi:aj/creators/zzz/summon/as_node/display4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.display4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.display5] run function dpi:aj/creators/zzz/summon/as_node/display5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.display5 set from storage animated_java:gu out
function dpi:aj/creators/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function dpi:aj/creators/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function dpi:aj/creators/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new