# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "dpi:aj/creators"
data modify storage animated_java:temp entry.data.rig_hash set value "f851eae5f0e2d707466aeb3e7101619d808b29f24233fbfd1f8f68f9f969e0ea"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=dpi.aj.creators.node.bth_head] run function dpi:aj/creators/zzz/summon/as_node/bth_head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bth_head set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.bth_brush] run function dpi:aj/creators/zzz/summon/as_node/bth_brush
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bth_brush set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.bth_right_hand] run function dpi:aj/creators/zzz/summon/as_node/bth_right_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bth_right_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.bth_left_hand] run function dpi:aj/creators/zzz/summon/as_node/bth_left_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bth_left_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.bth_display_ase] run function dpi:aj/creators/zzz/summon/as_node/bth_display_ase
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bth_display_ase set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.bth_display_subl] run function dpi:aj/creators/zzz/summon/as_node/bth_display_subl
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bth_display_subl set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_head] run function dpi:aj/creators/zzz/summon/as_node/ama_head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_head set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_right_hand] run function dpi:aj/creators/zzz/summon/as_node/ama_right_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_right_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_can] run function dpi:aj/creators/zzz/summon/as_node/ama_can
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_can set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_left_hand] run function dpi:aj/creators/zzz/summon/as_node/ama_left_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_left_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_display_vsc] run function dpi:aj/creators/zzz/summon/as_node/ama_display_vsc
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_display_vsc set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_display_nvim] run function dpi:aj/creators/zzz/summon/as_node/ama_display_nvim
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_display_nvim set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_kb_layer] run function dpi:aj/creators/zzz/summon/as_node/ama_kb_layer
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_kb_layer set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ama_kb] run function dpi:aj/creators/zzz/summon/as_node/ama_kb
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ama_kb set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_string] run function dpi:aj/creators/zzz/summon/as_node/ant_string
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_string set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_balloon] run function dpi:aj/creators/zzz/summon/as_node/ant_balloon
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_balloon set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_head] run function dpi:aj/creators/zzz/summon/as_node/ant_head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_head set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_baton] run function dpi:aj/creators/zzz/summon/as_node/ant_baton
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_baton set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_right_hand] run function dpi:aj/creators/zzz/summon/as_node/ant_right_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_right_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_left_hand] run function dpi:aj/creators/zzz/summon/as_node/ant_left_hand
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_left_hand set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_display_vsc] run function dpi:aj/creators/zzz/summon/as_node/ant_display_vsc
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_display_vsc set from storage animated_java:gu out
execute on passengers if entity @s[tag=dpi.aj.creators.node.ant_display_obs] run function dpi:aj/creators/zzz/summon/as_node/ant_display_obs
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ant_display_obs set from storage animated_java:gu out
function dpi:aj/creators/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function dpi:aj/creators/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function dpi:aj/creators/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new