# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove dpi.aj.creators.animation.main.playing
tag @s remove dpi.aj.creators.animation.idle_ant.playing
tag @s remove dpi.aj.creators.animation.busyant.playing