# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove dpi.aj.creators.animation.bth_busy.playing
tag @s remove dpi.aj.creators.animation.bth_idle.playing
tag @s remove dpi.aj.creators.animation.amandin_busy.playing
tag @s remove dpi.aj.creators.animation.amandin_idle.playing
tag @s remove dpi.aj.creators.animation.ant_busy.playing
tag @s remove dpi.aj.creators.animation.ant_blowing_balloon.playing
tag @s remove dpi.aj.creators.animation.ant_handout_to_busy.playing