# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute if score @s aj.mcf_tick_levitate.frame matches -1 run function dpi:aj/chest_house/animations/mcf_tick_levitate/zzz/function_keyframe_loop_patch
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.mcf_tick_levitate.frame
function dpi:aj/chest_house/animations/mcf_tick_levitate/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.mcf_tick_levitate.frame matches 79.. run return run scoreboard players set @s aj.mcf_tick_levitate.frame -1
scoreboard players add @s aj.mcf_tick_levitate.frame 1