# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.bth_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function dpi:aj/creators/animations/bth_idle/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove dpi.aj.creators.animation.bth_idle.playing