# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: 'fb932c3d074fcea9a3700b2dff7372d899e2233f0fd667c32b41bff490889d9c'}}} run function animated_java:global/remove/outdated_rig
function dpi:aj/creators/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack