# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ama_head) {transformation: [0.5f,-0.0907f,0.8613f,2.7249f,0f,0.9945f,0.1047f,0.5625f,-0.866f,-0.0524f,0.4972f,1.4063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ama_right_hand) {transformation: [0f,0.866f,0.5f,2.0296f,1f,0f,0f,0.125f,0f,0.5f,-0.866f,0.8605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ama_can) {transformation: [0f,0f,0f,2.0207f,0f,0f,0f,0.125f,0f,0f,0f,0.876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ama_left_hand) {transformation: [0f,0.866f,-0.5f,1.9046f,-1f,0f,0f,0.125f,0f,0.5f,0.866f,1.077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ama_kb_layer) {transformation: [0f,0f,0f,1.94f,0f,0f,0f,0.0938f,0f,0f,0f,0.9531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ama_kb) {transformation: [0f,0f,0f,1.94f,0f,0f,0f,0.0938f,0f,0f,0f,0.9531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}