# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=dpi_aj.chest_house.animation.chest_open.playing] run function dpi_aj:chest_house/animations/chest_open/zzz/on_tick
execute if entity @s[tag=dpi_aj.chest_house.animation.chest_close.playing] run function dpi_aj:chest_house/animations/chest_close/zzz/on_tick