# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage dpi:aj/springboard rig_hash set value '374443950caa7dbdeba07ecf9d04224d5e29aad84c67c1a9af6f6013b01b628b'
scoreboard objectives add aj.animation_springboard_prime.frame dummy
scoreboard objectives add aj.animation_springboard_bounce.frame dummy