# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function dpi:aj/chest_house/animations/json_file_in_30/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1