# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(baton) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,-0.0494f,0f,0f,-1f,-2.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,0.0131f,0f,0f,-1f,-3.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.0131f,0f,0f,-1f,-3.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head4) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5756f,0f,0f,-1f,-3.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}