# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove dpi.aj.lev_icons.animation.chest_open.playing
tag @s remove dpi.aj.lev_icons.animation.chest_close.playing
tag @s remove dpi.aj.lev_icons.animation.mcf_tick_levitate.playing
tag @s remove dpi.aj.lev_icons.animation.python_levitate.playing
tag @s remove dpi.aj.lev_icons.animation.structure_file_levitate.playing
tag @s remove dpi.aj.lev_icons.animation.json_file_levitate.playing