# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.json_file_in_42.frame 0
tag @s add aj.transforms_only
execute at @s run function dpi:aj/chest_house/animations/json_file_in_42/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove dpi.aj.chest_house.animation.json_file_in_42.playing