# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(baton) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,-0.1312f,0f,0f,-1f,-1.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,-0.0687f,0f,0f,-1f,-2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,-0.0687f,0f,0f,-1f,-2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head4) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.4938f,0f,0f,-1f,-2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(display4) {transformation: [-1.8333f,0f,0f,-1.375f,0f,1.8333f,0f,0.7125f,0f,0f,-1.8333f,-0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(display5) {transformation: [-1.8333f,0f,0f,1.375f,0f,1.8333f,0f,0.7125f,0f,0f,-1.8333f,-0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}