# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=dpi.aj.creators.root] run return run tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (dpi:aj/creators)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Function Not Executed as Root Entity',underlined:true},'\n\n ',{text:'[This Function]',color:yellow,hover_event:{action:show_text,value:[{color:yellow,text:'dpi:aj/creators/animations/ant_handout_to_busy/stop'}]}}," must be executed as the rig's root entity.",{text:'\n\n ≡ ',color:white,extra:[{text:'ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ',color:aqua,underlined:true,click_event:{action:suggest_command,command:'/execute as @e[tag=dpi.aj.creators.root] run function dpi:aj/creators/animations/ant_handout_to_busy/stop'}}]},['\n\n ',{italic:true,underlined:true,color:blue,text:'▶ Learn More ◀',click_event:{action:open_url,url:'https://animated-java.dev/docs/rigs/controlling-a-rig-instance'}}],'\n']
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function dpi:aj/creators/animations/pause_all
scoreboard players set @s aj.ant_handout_to_busy.frame 0
tag @s add aj.transforms_only
execute at @s run function dpi:aj/creators/animations/ant_handout_to_busy/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only