# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function dpi:aj/creators/animations/bth_busy/zzz/frames/last_frame_effects with storage animated_java:temp entry.data.uuids_by_name
scoreboard players add @s aj.bth_busy.frame 1