# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ant_string) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.125f,0f,0f,0f,-2.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_balloon) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,0.125f,0f,0f,0f,-2.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.625f,0f,0f,-1f,-3.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_baton) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.0731f,0f,0f,0f,-3.0608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_right_hand) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,0.0625f,0f,0f,-1f,-3.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_left_hand) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.0625f,0f,0f,-1f,-3.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_display_vsc) {transformation: [-1.7228f,-0.0546f,0.6247f,-1.375f,0f,1.8264f,0.1598f,0.8438f,-0.627f,0.1501f,-1.7162f,-1.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_display_obs) {transformation: [-1.7228f,0.0546f,-0.6247f,1.375f,0f,1.8264f,0.1598f,0.8438f,0.627f,0.1501f,-1.7162f,-1.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}