# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ant_string) {transformation: [0f,0f,0f,-0.4826f,0f,0f,0f,-0.1076f,0f,0f,0f,0.2299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_balloon) {transformation: [0f,0f,0f,-0.3837f,0f,0f,0f,-0.0785f,0f,0f,0f,0.1846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_head) {transformation: [0.0018f,0.0523f,0.9986f,0.1247f,0.0349f,0.998f,-0.0523f,0.3701f,-0.9994f,0.0349f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_baton) {transformation: [0f,0f,0f,0.0243f,0f,0f,0f,-0.3188f,0f,0f,0f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_right_hand) {transformation: [0f,0.0523f,0.9986f,0.0331f,0f,0.9986f,-0.0523f,-0.1835f,-1f,0f,0f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_left_hand) {transformation: [0f,0.0523f,0.9986f,0.0956f,0f,0.9986f,-0.0523f,-0.1867f,-1f,0f,0f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}