# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ant_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_baton) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,-0.3231f,0f,0f,0f,0.0642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_right_hand) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,-0.1875f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ant_left_hand) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,-0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}