# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.chest_open.frame
function dpi:aj/lev_icons/animations/chest_open/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.chest_open.frame matches 15.. run return run function dpi:aj/lev_icons/animations/chest_open/pause
scoreboard players add @s aj.chest_open.frame 1