# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove dpi_aj.chest_house.animation.chest_open.playing
tag @s remove dpi_aj.chest_house.animation.chest_close.playing